services:
  app:
    image: devops-nginx-app:latest
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - devops-net

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    command:
      - "--nginx.scrape-uri=http://app:80/stub_status"
    ports:
      - "9113:9113"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - devops-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - devops-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - devops-net

volumes:
  grafana-data:

networks:
  devops-net:
